services:
  - type: web
    name: generador-contenido-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9 